### ISSUE TITLE
Update .asi plugin

### ISSUE THREAD

**Issue by gromchek** [gta-chaos-mod/GUI-tool#8]
Update the asi plugin by GUI tool

**Comment by Lordmau5** [comment]
Not easily doable as sometimes new config options OR resources get added and I need to force those things onto the user as well.

One thing I could offer is an update *checker* that would link to the latest release on the ASI GitHub repo.
Would that be an idea?

**Comment by gromchek** [comment]
Yes, I think a link to the [release page](https://github.com/gta-chaos-mod/Trilogy-ASI-Script/releases/) would be enough

**Comment by Lordmau5** [comment]
Yeah that's what I was thinking - I'll see about implementing that

**Comment by Lordmau5** [comment]
Okay got a rather simple update checker in place now and as long as I stick to my tag versioning (as in, `v[major].[minor].[extra/build]`) it should continue to work as well.

Since GitHub's API requires you to provide an access token for authorization I have to grab the `/releases/latest` page as a string. Really dumb.

Either way, I then regex match one of the `href`'s on the page, create a `System.Version` variable out of it and compare that one to the one in the `Shared` class.

You can check on the code here: https://github.com/gta-chaos-mod/Trilogy-GUI-Tool/commit/f16ce5647f7e946e35fc00b74b903d6972278dd1

If you have a better way of handling it I'm all ears and would be happy to take that over my simple (maybe even terrible) implementation haha

**Comment by gromchek** [comment]
In my opinion, that's enough.

**Comment by Lordmau5** [comment]
Alright, I talked with another friend as well and he said it's good for this use-case

Optimally I still want to redo the UI, maybe I'll take another look at NeutralinoJS again and do it with Vuetify... not sure if I can do websocket servers with that though... (Similar to Electron, just way smaller since it uses the installed browser / WebView component)
